config/routes.rb
Rails.application.routes.draw do

  root 'pages#top'
  get '/feed/:id',to:'pages#feed',as: 'feed'
  get '/all_posts/:id',to:'pages#all_posts',as: 'all_posts'

  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    unlocks: "users/unlocks"
  }  
  devise_scope :user do
    get '/users',to: 'users#index',as: 'users'
    get 'user/:id',to: 'users#show',as: 'user'
  end

  get '/post',to: 'posts#new'
  post '/post',to: 'posts#create'
  get '/post/:id',to: 'posts#show',as: 'show_post'
  get '/post/:id/edit',to: 'posts#edit',as: 'edit_post'
  patch '/post/:id',to: 'posts#update'
  delete '/post/:id/delete',to: 'posts#delete',as: 'delete_post'
  post '/posts_search',to: 'posts#search'

  get '/bookmark/:id',to: 'bookmarks#add_bookmark',as: 'add_bookmark'
  get '/bookmark/:id/remove',to: 'bookmarks#remove_bookmark',as: 'remove_bookmark'
  
  get '/follow/:id',to: 'relationships#follow',as:'follow'
  get '/unfollow/:id',to: 'relationships#unfollow',as: 'unfollow'
  
  post '/comments',to:'comments#create'
  delete '/comemet/:id/delete',to:'comments#delete',as: 'delete_comment'

  get '/notifications/:id',to:'notifications#index',as: 'notifications'
  get '/notifications_history/:id',to:'notifications#history',as: 'notifications_history'  
  get '/mail_notification/:id',to: 'notifications#mail_notification_toggle',as: 'mail_notification'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :notifications, dependent: :destroy
  validates :content, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: :delete

  def create
    @comment = current_user.comments.new(comment_paramater)
    @post = Post.includes(comments: :user).find(comment_paramater[:post_id])
    @comments = @post.comments.includes(:user).recent.recent.page(params[:page]).per(15)
    if @comment.save
      send_notification_by(current_user,"comment") unless current_user.id == @post.user_id
      respond_to do |format|
        format.html {redirect_to show_post_path(@post)}
        format.js {render'comments/comments'}
      end
    else
      flash.now[:alert] = 'failed to post..... try again'
      render_after_failed
    end
  end


  def delete
      comment = Comment.find(params[:id])
      if comment.destroy
        flash.now[:notice] = 'コメントは削除されました。'
        redirect_to show_post_path(comment.post_id)
      else
        flash.now[:alert] = 'コメントは削除に失敗しました。もう一度お試しください'
        redirect_to show_post_path(comment.post_id, anchor: 'comment_#{comment.post_id}')
    end
  
  end

  private
    def comment_paramater
      params.require(:comment).permit(:content,:post_id)
    end

    def render_after_failed
      if (controller_path == 'posts' && action_name == 'show')
        render 'posts/show' and return
      elsif (controller_path == 'pages' && action_name == 'feed')
        render 'pages/feed' and return
      else
        redirect_to feed_path(current_user)
      end
    end

    def correct_user
      @comment = Comment.find(params[:id])
      redirect_to feed_path(current_user) unless current_user.id == @comment.user_id
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_form.html.erb
<%= form_with model: @comment do |f| %>
  <%= f.hidden_field :post_id, :value => @post.id %>
  <%= f.text_field :content ,id: 'comment_input'%>
  <div class="comment_btn">
    <%= f.submit 'comment',id: 'comment_btn'%>
  </div>
<% end %>

app/views/comments/_comments.html.erb
<% comments.each do |comment| %>
  <hr>
  <li class="comment" id ="comment_#{comment.id}">
    <p><%= link_to "#{comment.user.name}", user_path(comment.user) %><span class="commented_time"><%= time_ago_in_words(comment.created_at) %>前</span></p>
    <p class="comment-area"><%= comment.content %><p>
    <% if current_user.id == comment.user_id %>
      <div class="text_right">
        <%= link_to delete_comment_path(comment), data: { confirm: 'この投稿を削除しますか?' },method: :delete,class:"delete-btn" do %>
          <%= icon("fas", "trash-alt") %>
        <% end %>
      </div>
    <% end %>
  </li>
<% end %>
<%= paginate comments %>

app/views/comments/comments.js.erb
$("#comments").html("<%= j(render partial: 'comments/comments', locals: {comments: @comments}) %>")
$('#comment_input').val('');