config/routes.rb
Rails.application.routes.draw do

  root 'pages#top'
  get '/feed/:id',to:'pages#feed',as: 'feed'
  get '/all_posts/:id',to:'pages#all_posts',as: 'all_posts'

  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    unlocks: "users/unlocks"
  }  
  devise_scope :user do
    get '/users',to: 'users#index',as: 'users'
    get 'user/:id',to: 'users#show',as: 'user'
  end

  get '/post',to: 'posts#new'
  post '/post',to: 'posts#create'
  get '/post/:id',to: 'posts#show',as: 'show_post'
  get '/post/:id/edit',to: 'posts#edit',as: 'edit_post'
  patch '/post/:id',to: 'posts#update'
  delete '/post/:id/delete',to: 'posts#delete',as: 'delete_post'
  post '/posts_search',to: 'posts#search'

  get '/bookmark/:id',to: 'bookmarks#add_bookmark',as: 'add_bookmark'
  get '/bookmark/:id/remove',to: 'bookmarks#remove_bookmark',as: 'remove_bookmark'
  
  get '/follow/:id',to: 'relationships#follow',as:'follow'
  get '/unfollow/:id',to: 'relationships#unfollow',as: 'unfollow'
  
  post '/comments',to:'comments#create'
  delete '/comemet/:id/delete',to:'comments#delete',as: 'delete_comment'

  get '/notifications/:id',to:'notifications#index',as: 'notifications'
  get '/notifications_history/:id',to:'notifications#history',as: 'notifications_history'  
  get '/mail_notification/:id',to: 'notifications#mail_notification_toggle',as: 'mail_notification'
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user_page, only: [:index,:history,:mail_notificatioin_toggle]

  def index
    @notifications = Notification.includes(:sender,:post,:comment).where(reciever_id: current_user.id).recent.page(params[:page]).per(15)
    # @notifications = current_user.passive_notifications.includes(:sender,:post,:comment).where(reciever_id:current_user.id,checked: false).recent.page(params[:page]).per(15)
    # Notification.where(reciever_id:current_user.id,checked: false).update(checked: true)
  end

  def history
    @notifications = current_user.passive_notifications.includes(:sender,:post,:comment).recent.page(params[:page]).per(15)
    render 'notifications/index'
  end

  def mail_notification_toggle
    user = User.find(params[:id])
    if user.notification
      user.update(notification: false) if user.valid?
      flash.now[:notice] = 'メール通知をOFFにしました。'
    else
      user.update(notification: true) if user.valid?
      flash.now[:notice] = 'メール通知をONにしました。'
    end
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper

  def notificatioin_detail(notification)
    sender = link_to notification.sender.name, notification.sender
    post = link_to 'あなたの投稿', show_post_path(notification.post) if notification.post_id
    case notification.action
      when "follow" then
        "#{sender}があなたをフォローしました。"
      when "bookmark" then
        "#{sender}が#{post}をお気に入りに入れました。"
      when "comment" then
        "#{sender}が#{post}にコメントしました。"
    end
  end

  def unchecked_notifications
    current_user.passive_notifications.exists?(:checked => false)
  end
end

app/views/notifications/_mail_notification_toggle.html.erb
<% if current_user.notification %>
  <%= link_to 'メール通知:ON', mail_notification_path(current_user), remote: true %>
<% else %>
  <%= link_to 'メール通知:OFF', mail_notification_path(current_user), remote: true %>
<% end %>

app/views/notifications/_notification.html.erb
<li class ="notification">
  <p class="notification_detail"><%== notificatioin_detail(notification) %><span><%= "(#{time_ago_in_words(notification.created_at)}前)" %></span></p>
  <% unless notification.comment.nil? %>
    <p class="notification_comment"><%= notification.comment.content %></p>
  <% end %>
</li>

app/views/notifications/index.html.erb
<% if current_page?(action: 'index') %>
  <%= provide(:title,"通知一覧") %>
<% else %>
  <%= provide(:title,"通知履歴") %>
<% end %>
<div>
  <p id="notification_title"><%= yield(:title) %></p>
  <ul class="notifications_index scroll_list jscroll">
    <%= render @notifications %>
    <%= paginate @notifications %>
  </ul>
</div>

app/views/notifications/mail_notification_toggle.js.erb
$("#mail_notification_toggle").html("<%= j(render 'notifications/mail_notification_toggle') %>")

app/views/notifications/notification_history.js.erb
$("#notifications").html("<% j(render partial: 'notifications/notificatins', locals: {notificaioins: @notificaions}) %>")