config/routes.rb
Rails.application.routes.draw do

  root 'pages#top'
  get '/feed/:id',to:'pages#feed',as: 'feed'
  get '/all_posts/:id',to:'pages#all_posts',as: 'all_posts'

  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    unlocks: "users/unlocks"
  }  
  devise_scope :user do
    get '/users',to: 'users#index',as: 'users'
    get 'user/:id',to: 'users#show',as: 'user'
  end

  get '/post',to: 'posts#new'
  post '/post',to: 'posts#create'
  get '/post/:id',to: 'posts#show',as: 'show_post'
  get '/post/:id/edit',to: 'posts#edit',as: 'edit_post'
  patch '/post/:id',to: 'posts#update'
  delete '/post/:id/delete',to: 'posts#delete',as: 'delete_post'
  post '/posts_search',to: 'posts#search'

  get '/bookmark/:id',to: 'bookmarks#add_bookmark',as: 'add_bookmark'
  get '/bookmark/:id/remove',to: 'bookmarks#remove_bookmark',as: 'remove_bookmark'
  
  get '/follow/:id',to: 'relationships#follow',as:'follow'
  get '/unfollow/:id',to: 'relationships#unfollow',as: 'unfollow'
  
  post '/comments',to:'comments#create'
  delete '/comemet/:id/delete',to:'comments#delete',as: 'delete_comment'

  get '/notifications/:id',to:'notifications#index',as: 'notifications'
  get '/notifications_history/:id',to:'notifications#history',as: 'notifications_history'  
  get '/mail_notification/:id',to: 'notifications#mail_notification_toggle',as: 'mail_notification'
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :img, ImgUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, foreign_key: "bookmarked_post_id", dependent: :destroy
  has_many :users, through: :bookmarks
  has_many :notifications, dependent: :destroy
  validates :user_id ,presence: true
  validates :img ,presence: true
  validates :title ,{presence: true, length: {maximum: 256}}

  def self.search(keywords_params,current_page_params,user_id,user)
      return posts = Post.get_all_posts(current_page_params,user_id,user) if keywords_params == ""
    keywords = keywords_params.split(/[[:blank:]]+/)
    posts = []
    keywords.each do |keyword|
      next if keyword == ""
      posts += Post.get_searched_result(keywords_params,current_page_params,user_id,user)
    end
    # uniq!だと、変更がない場合、nilを返してしまう
    posts = posts.uniq
  end

   def self.get_searched_result(keyword,current_page,user_id,user)
    case current_page
    when 'all_posts' then
      where('title LIKE ? ',"%#{keyword}%")
    when 'feed' then
      where("(user_id IN ?) AND (title LIKE ?)",user.following_ids,"%#{keyword}%")
    when 'show'
      where("(user_id = ?) AND (title LIKE ?)", user_id.to_i,"%#{keyword}%")
    end
  end

  def self.get_all_posts(current_page,user_id,user)
    case current_page
    when 'all_posts' then
      Post.all.recent 
    when 'feed' then
      Post.where("user_id IN (?)",user.following_ids).recent 
    when 'show'
      Post.where(user_id: user_id.to_i).recent
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit,:update,:delete]
  def new
    @post = Post.new 
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash.now[:notice] = 'post successfully!'
      redirect_to show_post_path(@post)
    else
      flash.now[:alert] = 'failed to post.... try again'
      render 'new'
    end
  end

  def show
    @post = Post.includes(:user).find(params[:id])
    @comments = @post.comments.includes(:user).recent.page(params[:page]).per(15)
    @comment = Comment.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.update!(post_params)
      flash.now[:notice] = "投稿画像を編集しました。"
      redirect_to user_path(current_user)
    else
      flash.now[:alert] = "編集内容が正常に保存されませんでした。"
      render :edit
    end
  end

  def delete
    if Post.find(params[:id]).destroy
      flash.now[:notice] = "投稿は削除されました"
      redirect_to user_path(current_user)
    else
      flash.now[:alert] = "投稿の削除に失敗しました"
    end

  end

  def search
    @user = User.find(params[:page_user_id])
    @current_user = current_user
    post_ids = Post.search(params[:keyword],params[:current_page],@user.id,@current_user)
    @posts = Post.where("id IN (?)",post_ids).recent
    respond_to do |format|
      format.html {redirect_to feed_path(current_user)}
      format.js
    end
  end

  private 
    def post_params
      params.require(:post).permit(:img, :title, :img_chahe)
    end

    def correct_user
      @post = Post.find(params[:id])
      redirect_to feed_path(current_user) unless current_user.id == @post.user_id
    end
    

end

app/helpers/posts_helper.rb
module PostsHelper
 
end

app/views/posts/_action_btn.html.erb
<% if current_user.id == @post.user_id %>
  <ul class="text-right">
    <li class="inline">
      <%= link_to edit_post_path(@post),class:"edit-btn" do %>
        <%= icon("fas", "edit") %>
      <% end %>
    </li>
    <li class="inline">
    <%= link_to delete_post_path(@post), data: { confirm: 'この投稿を削除しますか?' },method: :delete,class:"delete-btn" do %>
        <%= icon("fas", "trash-alt") %>
      <% end %>
    </li>
  </ul>
<% else %>
  <div id="bookmark_<%= @post.id %>" class="text_right" >
    <%= render partial: 'bookmarks/bookmark_btn', locals: {post: @post} %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= link_to show_post_path(post), remote: true do %>
  <%= image_tag post.img.to_s, class:"post_img" %>
<% end %>

app/views/posts/_post_form.html.erb
<div class="upload_wrapper">
<%= form_with model: post ,url: post_path(post), builder: CustomFormBuilder, local: true do |f| %>
  <div class="field img_uploader">
    <div id="prev_img_box" class="hidden">
      <img id="prev_img" src="#" class='hidden' /> 
    </div>
    <% if post.img? %>
      <%= image_tag post.img.to_s, class:'present_img' %>
      <%= f.hidden_field :post_id, :value => post.id %>
    <% else %>
      <%= f.hidden_field :img_cache %>
      <img class="present_img" src="https://kukuhana.s3-ap-northeast-1.amazonaws.com/no_img.jpg" />
    <% end %> 
    <%= f.file_field :img, id: 'post_img' %>
    <p class="title"><%= f.label :title %></p>
    <p><%= f.text_area :title %></p>
    <%= f.submit yield(:action) ,id: "submit_btn" %>
  </div>
<% end %>
</div>

app/views/posts/_posts_index.html.erb
<% posts.each do |post| %>
  <div class="post">
    <%= render partial: 'posts/post' ,locals: {post: post} %>
  </div>
<% end %>

app/views/posts/_show_post.html.erb
<div id ="img">
  <%= link_to show_post_path(@post) do %>
    <%= image_tag @post.img.to_s, class:"show_post_img" %>
  <% end %>
</div>
<div id ="post_contents">
  <div class="post_info">
    <p class="posted_time"><%= @post.created_at.strftime('%Y/%m/%d %H:%M') %></p>
    <p>Posted by <%= link_to "#{@post.user.name}", user_path(@post.user_id) %></p>
    <p><%= simple_format(text_url_to_link(h(@post.title)).html_safe) %></p>
  <%= render 'posts/action_btn' %>
  </div>
  <div class="comments_area">
    <%= render 'comments/comment_form' %>
    <ul id="comments" class="comment_jscroll scroll_list">
      <%= render partial: 'comments/comments', locals: {comments: @comments} %>
    </ul>
  </div>
</div>

app/views/posts/edit.html.erb
<%= provide(:title,"投稿編集") %>
<%= provide(:action,"更新") %>
<%= render partial: 'posts/post_form', locals: {post: @post} %>

app/views/posts/new.html.erb
<%= provide(:title,"画像アップロード") %>
<%= provide(:action,"作成") %>
<%= render partial: 'posts/post_form', locals: {post: @post}%>

app/views/posts/search.js.erb
$("#posts_index").html("<%= j(render partial: 'posts/posts_index', locals:{posts: @posts}) %>")

app/views/posts/show.html.erb
<%= provide(:title,"詳細ページ") %>
<div id="show_post">
  <%= image_tag @post.img.to_s, class:"post_img" %>
  <%= render 'posts/action_btn' %>
  <div class="comment_form">
    <%= render 'comments/comment_form' %>
  </div>
  <ul id="comments" class="comment_jscroll scroll_list">
    <%= render partial: 'comments/comments', locals: {comments: @comments} %>
  </ul>
</div>

app/views/posts/show.js.erb
$("#modal").html("<%= j(render partial: 'posts/show_post', locals: {comments: @comments}) %>")
$('#modalArea').fadeIn()