config/routes.rb
Rails.application.routes.draw do

  root 'pages#top'
  get '/feed/:id',to:'pages#feed',as: 'feed'
  get '/all_posts/:id',to:'pages#all_posts',as: 'all_posts'

  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    unlocks: "users/unlocks"
  }  
  devise_scope :user do
    get '/users',to: 'users#index',as: 'users'
    get 'user/:id',to: 'users#show',as: 'user'
  end

  get '/post',to: 'posts#new'
  post '/post',to: 'posts#create'
  get '/post/:id',to: 'posts#show',as: 'show_post'
  get '/post/:id/edit',to: 'posts#edit',as: 'edit_post'
  patch '/post/:id',to: 'posts#update'
  delete '/post/:id/delete',to: 'posts#delete',as: 'delete_post'
  post '/posts_search',to: 'posts#search'

  get '/bookmark/:id',to: 'bookmarks#add_bookmark',as: 'add_bookmark'
  get '/bookmark/:id/remove',to: 'bookmarks#remove_bookmark',as: 'remove_bookmark'
  
  get '/follow/:id',to: 'relationships#follow',as:'follow'
  get '/unfollow/:id',to: 'relationships#unfollow',as: 'unfollow'
  
  post '/comments',to:'comments#create'
  delete '/comemet/:id/delete',to:'comments#delete',as: 'delete_comment'

  get '/notifications/:id',to:'notifications#index',as: 'notifications'
  get '/notifications_history/:id',to:'notifications#history',as: 'notifications_history'  
  get '/mail_notification/:id',to: 'notifications#mail_notification_toggle',as: 'mail_notification'
end

app/views/layouts/_after_login.html.erb
<div id ="logo" >
  <%= link_to 'Faketagram', feed_path(current_user) %>
</div>
<ul id="header_menu">
  <li class="pc">
    <%= render 'layouts/search' %>
  </li>
  <li id="upload_link", class="link pc">
    <%= link_to 'Upload',post_path %>
  </li>
  <li id ="push" class="link pc">
    <%= link_to '通知', notifications_path(current_user) %>
    <% if unchecked_notifications %>
      <%= icon("fas", "bell") %>
    <% end %>
  </li>
  <li class="user_menu_btn link pc">
    <%= icon("fas", "user open_user_menu") %>
  </li>
  <div class="user_menu_btn sp-menu sp">
    <%= icon("fas", "bars open_user_menu") %>
  </div>
</ul>

app/views/layouts/_before_login.html.erb
<div id = "logo">
  <%= link_to 'Faketagram' ,"/" %>
</div>
<ul id="before_header_menu">
  <li class="login">
    <%= link_to 'ログイン', new_user_session_path %>
  </li>
  <%= link_to new_user_registration_path do %>
    <li class="register">登録</li>
  <% end %>
<ul>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div id="notice">
    <p class="flash_icon"><%= icon("far", "laugh") %></p>
    <p class="flash_message"><%= flash[:notice] %></p>
  </div>
<% elsif flash[:alert] %>
  <div id="alert">
    <p class="flash_icon"><%= icon("far", "dizzy") %></p>
    <p class="flash_message"><%= flash[:alert] %></p>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<% if user_signed_in? %>
  <p><%= link_to '画像をアップロードしよう！', post_path %></p>
<% end %>
<p class="copy">&copy; 2019 Faketagram</p>

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <%= render 'layouts/after_login' %>
<% else %>
  <%= render 'layouts/before_login' %>
<% end %>

app/views/layouts/_modal.html.erb
<div id="modalBg" class="modalBg"></div>
<div class="modalWrapper">
  <div class="modalContents" id="modal"></div>
  <div id="closeModal" class="closeModal">×</div>
</div>

app/views/layouts/_search.html.erb
<%= form_with url: posts_search_path ,id:'formSearch' do |f| %>
  <%= f.text_field :keyword ,id:"keyword_input" %>
  <%= f.hidden_field :current_page ,:value => action_name %>
  <% if @user %>
    <%= f.hidden_field :page_user_id ,:value => @user.id %>
  <% end %>
  <%= f.submit '検索' ,id:"search_btn" %>
<% end %>

app/views/layouts/_user_menu.html.erb
<div id="user_menu_bg" class="user_menu_bg"></div>
<div id="user_menu_wrapper">
  <ul id="user_menu">
    <li>
      <%= link_to 'プロフィール',user_path(current_user) %>
    </li>
    <li id ="mail_notification_toggle">
      <%= render 'notifications/mail_notification_toggle' %>
    </li>
    <li id="upload_link", class="link sp">
    <%= link_to 'Upload',post_path %>
    </li>
    <li id ="push" class="link sp">
      <%= link_to '通知', notifications_path(current_user) %>
      <% if unchecked_notifications %>
        <%= icon("fas", "bell") %>
      <% end %>
    </li>
    <li>
      <%= link_to 'ログアウト', destroy_user_session_path ,method: :delete %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
   <%= render 'layouts/head' %>
  </head>
  <header>
  <%= render 'layouts/header' %>
  </header>
  <%= render 'layouts/flash' %>
  <section id="modalArea">
    <%= render 'layouts/modal' %>
  </section>
  <section id="user_menu_area">
    <%= render 'layouts/user_menu' if user_signed_in? %>
  </section>
  <body>
  <div class="wrapper">
      <%= yield %>
    </body>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </div>
</html>